name: blocdisk
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  http: ^1.1.0
  web3dart: ^2.7.1
  file_picker: ^5.3.3
  fluttertoast: ^8.2.2
  http_parser: ^4.0.2
  url_launcher: ^6.1.12
  walletconnect_flutter_v2: ^2.1.3
  path_provider: ^2.1.0
  open_file_plus: ^3.4.1
  permission_handler: ^10.4.3
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^8.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/abi.json
    - assets/icons/file_icon.png
  
  

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
